# python
- 컴퓨터의 CPU, RAM, SSD를 활용하기 위해서 학습
1. 변수선언: RAM 사용 문법 : 식별자(저장공간을 구분하는 문자열) : PEP20, PEP8(autopep8-코딩 스타일 가이드, flack8-if/for문 많이 쓰면 적게 쓰라고 알려줌)
2. 데이터 타입: RAM 효율적 사용 문법 : int, float, bool, str, list, tuple, dict, set
3. 연산자: CPU 사용 문법 : 산술, 비교, 논리, 할당, 멤버 ...
4. 조건문, 반복문 : if, elif, else : while, for break, continue, range() ...
5. 함수: 반복 사용되는 코드를 묶어서 코드 작성 및 실행 : def, return, scope(global), lambda ...
6. 클래스: 변수, 함수를 묶어서 코드 작성 실행 : 객체 지향 구현 : class, self, special methods(생성자)
7. 모듈: 변수, 함수, 클래스를 파일로 묶어서 코드 작성 실행 : 확장자 .py
8. 패키지: 여러개의 모듈을 디렉토리로 묶어서 관리 : 버전 정보 : import, from, as
9. 입출력: SSD를 사용하는 문법 : RAM(object) > SSD(file), SSD(file) > RAM(object) : pickle

In [3]:
# import this

# Class
- 변수, 함수를 묶어서 코드 작송 및 실행
- 객체지향 구현: 실제 세계를 모델링하여 프로그램을 개발하는 개발 방법론: 협업이 용이함
- 함수 사용: 함수선언(코드 작성) > 함수호출(코드 실행)
- 클래스 사용
  - 클래스 선언(코드 작성:설계도 작성) > 객체 생성(메모리 사용:제품 생산) > 메서드 실행(코드 실행:제품 사용)
  - 메서드: 클래스 안에 선언되는 함수
- class의 식별자: UpperCamelCase, PascalCase(0), snake_case(X: 변수, 함수 선언 시 사용)

In [10]:
# 1. 클래스 선언: 코드 작성
# 예금 계좌: Account: balance, deposit(), withdraw()
class Account:
    
    balance = 0
    
    # 입금 코드 구현
    def deposit(self, amount):
        self.balance += amount
        
    # 출금 코드 구현
    def withdraw(self, amount):
        self.balance -= amount

In [12]:
# 2. 객체 생성: 메모리 사용
acc1 = Account()
acc2 = Account()

In [14]:
# dir(): 객체 안에 들어있는 변수들, 함수 목록 출력
dir(acc1)[-3:], dir(acc2)[-3:]

(['balance', 'deposit', 'withdraw'], ['balance', 'deposit', 'withdraw'])

In [18]:
acc1.balance = 1000  # 객체 안 숫자 바꾸기 0 -> 1000

In [20]:
acc1.balance, acc2.balance

(1000, 0)

In [ ]:
# 3. 메서드 실행: 코드 실행

In [22]:
acc1.balance, acc2.balance  # 1번 계좌에는 1000원, 2번 계좌에는 0원이 들어있다.

(1000, 0)

In [24]:
acc1.withdraw(600)
acc2.deposit(3000)

In [26]:
acc1.balance, acc2.balance  # 1번 계좌에는 1000원에서 600원을 출금했고, 2번 계좌에는 0원에서 3000원을 입금했다.

(400, 3000)

In [ ]:
# pandas DataFrame
# 클래스선언(다른사람) > 객체생성(사용1) > 메서드호출(사용2)

In [28]:
# 1. 클래스선언 : 다른 사람이 만든 클래스 가져옴
import pandas as pd

In [30]:
# 2. 객체생성
df = pd.DataFrame({'id': list('123'), 'name': list('ABC')})
df

  id name
0  1    A
1  2    B
2  3    C

In [40]:
# 3. 메서드호출
# dir(df)
# help(df.sum)
df.sum()

id      123
name    ABC
dtype: object

In [42]:
df.T

      0  1  2
id    1  2  3
name  A  B  C

In [54]:
# acc 객체 클래스: Account: balance, withdraw(), deposit()
# acc 객체 데이터 타입: Account
# > 클래스는 데이터 타입 입니다.
# Account 클래스는 우리가 만듦: 사용자 정의
# > 클래스는 사용자 정의 데이터 타입 입니다.
acc = Account()
type(acc)

__main__.Account

In [56]:
# data1 객체 데이터타입: str
# data1 객체 클래스: str: upper(), lower(), join() ...
data1 = 'python'
type(data1)

str

In [64]:
dir(data1)[-3:]

['translate', 'upper', 'zfill']

In [60]:
# data2 객체 데이터타입, 클래스 list
data2 = [1, 3, 2]
type(data2)

list

In [ ]:
# > 객체는 어떤 데이터타입(클래스)인지에 따라서 사용 가능한 변수, 메서드가 달라진다.

In [58]:
import numpy as np
arr = np.array([1, 2, 3])
type(arr), arr

(numpy.ndarray, array([1, 2, 3]))

In [76]:
%reset
# 현재 선언된 변수 초기화

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y

In [78]:
# 변수, 함수는 둘다 객체입니다.
data = 1

In [80]:
def plus():
    return 1+2

In [82]:
type(data), type(plus), type(plus())

(int, function, int)

In [84]:
%whos
# 현재 선언된 객체 목록 출력

Variable               Type        Data/Info
--------------------------------------------
data                   int         1
dataframe_columns      function    <function dataframe_colum<...>ns at 0x00000268CA952200>
dataframe_hash         function    <function dataframe_hash at 0x00000268CA950C20>
dtypes_str             function    <function dtypes_str at 0x00000268CA950E00>
get_dataframes         function    <function get_dataframes at 0x00000268C80AE8E0>
getpass                module      <module 'getpass' from 'C<...>conda3\\Lib\\getpass.py'>
hashlib                module      <module 'hashlib' from 'C<...>conda3\\Lib\\hashlib.py'>
import_pandas_safely   function    <function import_pandas_s<...>ly at 0x00000268C80ACCC0>
is_data_frame          function    <function is_data_frame at 0x00000268C80AEF20>
json                   module      <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
plus                   function    <function plus at 0x00000268C97C3920>

In [86]:
# special methods
# - 특별한 기능을 하는 메서드
# - 앞뒤로 __가 붙은 메서드
# - 대표적으로 생성자 메서드

In [96]:
# 생성자 메서드: __init__(self)
# - 특별한 기능: 객체 생성 시 실행되는 메서드

In [140]:
# 1. 클래스 선언
class Account:
    # "생성자 메서드" !!: 메서드에서 사용되는 변수의 초기값 설정하는 용도 사용
    def __init__(self, balance):  
        self.balance = balance
    
    # 입금 코드 구현
    def deposit(self, amount):
        self.balance += amount
        
    # 출금 코드 구현
    def withdraw(self, amount):
        self.balance -= amount

In [124]:
# 객체 생성: 메모리 사용: 원자재 사용
acc = Account(1000)  # balance 변수에 값 1000을 넣는다.(초기값 설정)

In [126]:
# 메서드 호출: 불량품 생산
acc.deposit(1000)

In [128]:
acc.balance

2000

In [130]:
# mabgling(private variable), getter, setter 내용을 같이

In [132]:
d1, d2 = 1, 2
d3, d4 = '3', '4'

In [134]:
type(d1), type(d2), type(d3), type(d4)

(int, int, str, str)

In [138]:
# 데이터 타입이 다르면 같은 연산자라도 다르게 연산이 수행됩니다.
d1+d2, d3+d4

(3, '34')

In [146]:
# __add__ : + 연산자에 대한 코드 정의
# dir(d1)
d1.__add__ (d2) # int 클래스의 __ add __ () 메서드 호출

3

In [148]:
# dir(d3)
d3.__add__ (d4) # str 클래스의 __add__ () 메서드 호출

'34'

__add__ 메서드는 두 객체를 더할 때 호출되는 특수 메서드이다.   
하지만 여기서 "덧셈"을 구현한 것이 아니라, self.data에서 obj.data를 빼는 연산을 수행하고 있다.   
즉, num1 + num2는 num1.data에서 num2.data를 빼는 연산이 수행되고, 그 결과를 반환한다.

In [156]:
class Number:
    def __init__(self, data):
        self.data = data
    def __add__ (self, obj):  # 인스턴스 메서드이기 때문에 객체를 만들어야 호출할 수 있다.
        self.data -= obj.data
        return self.data

In [158]:
num1 = Number(3)
num2 = Number(2)

In [163]:
# num1 + num2는 num1.__add__(num2)로 해석된다.
# num1은 메서드를 호출한 주체이므로 self에 대응된다.
# num2는 + 연산에서 두 번째 피연산자이므로, __add__ 메서드의 두 번째 인자인 obj에 전달된다.

# num1 .__add__(num2) : num1 객체의 __add__ 메서드 호출 num2 는 파라미터로 들어감
num1+num2  # 3-2 = 1

-1