<center><img src='https://raw.githubusercontent.com/Jangrae/img/master/ml_python.png' width=600/></center>

<img src = "https://github.com/Jangrae/img/blob/master/medical2.png?raw=true" width=800 align="left"/>

# 실습 내용

- 다양한 알고리즘으로 성능이 최적화된 모델을 만듭니다.
- 성능이 좋을 것으로 예상되는 모델을 선정해 새로운 데이터에 대해 예측을 수행합니다.

# 1.환경 준비

- 기본 라이브러리와 대상 데이터를 가져와 이후 과정을 준비합니다.

In [4]:
# 라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import warnings

warnings.filterwarnings(action='ignore')
%config InlineBackend.figure_format = 'retina'

- 학습용 데이터를 불러옵니다.
- 평가용 데이터는 이후에 불러오게 됩니다.

In [5]:
# 학습용 데이터 불러오기
path = 'https://raw.githubusercontent.com/jangrae/csv/master/insurance_train.csv'
data = pd.read_csv(path)

# 2.데이터 이해

- 분석할 데이터를 충분히 이해할 수 있도록 다양한 탐색 과정을 수행합니다.

**데이터 설명**

- age: 나이
- sex: 성별(female, male)
- bmi: 체질량지수(체중을 키의 제곱으로 나눈 값, 적정수준:18.5 - 24.9)
- children: 자녀 수
- smoker: 흡연 여부
- region: 거주지역(northeast, southeast, southwest, northwest)
- **charges: 건강보험에서 지불한 의료비 - Target**

In [9]:
# 데이터 살펴보기
data.head()

   age     sex     bmi  children smoker     region     charges
0   41  female  31.600         0     no  southwest   6186.1270
1   30    male  25.460         0     no  northeast   3645.0894
2   18  female  30.115         0     no  northeast  21344.8467
3   61  female  29.920         3    yes  southeast  30942.1918
4   34  female  27.500         1     no  southwest   5003.8530

In [13]:
# 기술통계 확인
data.describe()

               age          bmi     children       charges
count  1238.000000  1238.000000  1238.000000   1238.000000
mean     39.236672    30.648522     1.096931  13164.000669
std      13.984795     6.129289     1.203057  11994.023291
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.220000     0.000000   4755.809850
50%      40.000000    30.305000     1.000000   9333.014350
75%      51.000000    34.496250     2.000000  16443.294663
max      64.000000    53.130000     5.000000  63770.428010

In [34]:
# 상관관계 
# data.corr()

In [40]:
# Target 분포 확인
data.value_counts('charges')

charges
1639.56310     2
12644.58900    1
12829.45510    1
12815.44495    1
12797.20962    1
              ..
6289.75490     1
6282.23500     1
6250.43500     1
6238.29800     1
63770.42801    1
Name: count, Length: 1237, dtype: int64

In [38]:
# 흡연자 비율
data.value_counts('smoker')

smoker
no     991
yes    247
Name: count, dtype: int64

In [42]:
# 남녀 비율
data.value_counts('sex')

sex
male      627
female    611
Name: count, dtype: int64

# 3.데이터 준비

- 전처리 과정을 통해 머신러닝 알고리즘에 사용할 수 있는 형태의 데이터를 준비합니다.

**1) x, y 분리**

In [44]:
# x, y 분리
target = 'charges'

x = data.drop(columns = target)
y = data.loc[:,target]

In [46]:
# 확인
x.head(2)

   age     sex    bmi  children smoker     region
0   41  female  31.60         0     no  southwest
1   30    male  25.46         0     no  northeast

**2) 가변수화**

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1238 entries, 0 to 1237
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1238 non-null   int64
 1   sex       1238 non-null   object
 2   bmi       1238 non-null   float64
 3   children  1238 non-null   int64
 4   smoker    1238 non-null   object
 5   region    1238 non-null   object
 6   charges   1238 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 67.8+ KB

In [50]:
# 가변수화
dum_cols = ['sex', 'smoker', 'region']

x = pd.get_dummies(x, columns = dum_cols, drop_first=True, dtype=int)

# 확인
x.head()

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,41,31.600,0,0,0,0,0,1
1,30,25.460,0,1,0,0,0,0
2,18,30.115,0,0,0,0,0,0
3,61,29.920,3,0,1,0,1,0
4,34,27.500,1,0,0,0,0,1

**3) 학습용, 평가용 데이터 분리**

In [52]:
# 학습용, 평가용 데이터 분리
from sklearn.model_selection import train_test_split

# 검증 데이터 나누기
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.3, random_state=1)

# 4.모델링

- 하이퍼파라미터 최적화 과정을 통해 최선의 성능을 갖는 모델을 만들고 성능을 검증합니다.
- 각 모델을 joblib.dump() 함수를 사용해 저장합니다.

In [ ]:
# xgboost 설치
# !pip install xgboost

In [ ]:
# lightgbm 설치
# !pip install lightgbm

- 이후 사용할 함수를 모두 불러옵니다.

In [77]:
# 불러오기

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor

from sklearn.metrics import *

from sklearn.model_selection import GridSearchCV

**1) Linear Regression**

- Linear Regression 알고리즘으로 모델링하고 성능을 검증합니다.
- 모델을 파일로 저장힙니다.

In [87]:
# 모델링
model = LinearRegression()   # LinearRegression 모델은 하이퍼파라미터 튜닝이 안된다. --> 그리드 서치, 랜덤서치 사용X

# 학습하기
model.fit(x_train, y_train)

# 예측하기
y_val_pred = model.predict(x_val)   # 검증 데이터로 예측

# 평가하기
print('MAE:', mean_absolute_error(y_val, y_val_pred))
print('R2:', r2_score(y_val, y_val_pred))

MAE: 4504.899290809304
R2: 0.7354118142143975

In [62]:
# 모델저장
joblib.dump(model, 'model_linear.pkl')

['model_linear.pkl']

**2) Decision Tree**

- 하이퍼파라미터 최적화 과정을 통해 최선의 성능을 갖는 Decision Tree 모델을 만들고 성능을 검증하세요.
- 변수 중요도를 시각화해 확인하고, 모델을 파일로 저장힙니다.

In [91]:
# 파라미터 선언
param = {'max_depth': range(1, 21)}

model = GridSearchCV(DecisionTreeRegressor(),
                    param,
                    cv=5)

# 학습하기
model.fit(x_train, y_train) 

# 최고 파라미터, 최고 성능 확인
print('최적파라미터:', model.best_params_)
print('-' * 80)
print('최고성능:', model.best_score_)
print('=' * 80)

# 예측하기
y_val_pred = model.predict(x_val)

# 평가하기
print('MAE:', mean_absolute_error(y_val, y_val_pred))
print('R2:', r2_score(y_val, y_val_pred))

# max_depth가 4로 나온 것은 트리가 한번만 뻗은 것이다.  -> 문제가 있는 것이니 다시 확인해보기

최적파라미터: {'max_depth': 4}
--------------------------------------------------------------------------------
최고성능: 0.8317266890075053
================================================================================
MAE: 2741.4807110024926
R2: 0.853678773048376

In [85]:
# 변수 중요도 시각화

In [93]:
# 모델저장
joblib.dump(model, 'model_tree.pkl')

['model_tree.pkl']

**3) Random Forest**

- 하이퍼파라미터 최적화 과정을 통해 최선의 성능을 갖는 Random Forest 모델을 만들고 성능을 검증하세요.
- 변수 중요도를 시각화해 확인하고, 모델을 파일로 저장힙니다.

In [96]:
# 파라미터 선언
param = {'max_depth': range(1, 21)}

model = GridSearchCV(RandomForestRegressor(),
                     param,
                     cv = 5)

# 학습하기 
model.fit(x_train, y_train)

# 최적 파라미터, 최고 성능 확인
print('최적파라미터:', model.best_params_)
print('-' * 80)
print('최고성능:', model.best_score_)
print('=' * 80)

# 예측하기
y_val_pred = model.predict(x_val)

# 평가하기
print('MAE:', mean_absolute_error(y_val, y_val_pred))
print('R2:', r2_score(y_val, y_val_pred))

최적파라미터: {'max_depth': 4}
--------------------------------------------------------------------------------
최고성능: 0.843982045189341
================================================================================
MAE: 2665.0109424864827
R2: 0.8563636620134754

In [ ]:
# 변수 중요도 시각화

In [98]:
# 모델저장
joblib.dump(model, 'model_forest.pkl')

['model_forest.pkl']

**4) LightGBM**

- 하이퍼파라미터 최적화 과정을 통해 최선의 성능을 갖는 LightGBM 모델을 만들고 성능을 검증하세요.
- 변수 중요도를 시각화해 확인하고, 모델을 파일로 저장힙니다.

In [104]:
# 파라미터 선언
param = {'max_depth': range(1, 21)}

model = GridSearchCV(LGBMRegressor(verbose=-1),
                     param,
                     cv = 5)

# 학습하기 
model.fit(x_train, y_train)

# 최적 파라미터, 최고 성능 확인
print('최적파라미터:', model.best_params_)
print('-' * 80)
print('최고성능:', model.best_score_)
print('=' * 80)

# 예측하기
y_val_pred = model.predict(x_val)

# 평가하기
print('MAE:', mean_absolute_error(y_val, y_val_pred))
print('R2:', r2_score(y_val, y_val_pred))

최적파라미터: {'max_depth': 2}
--------------------------------------------------------------------------------
최고성능: 0.8483491457389933
================================================================================
MAE: 2757.179977031174
R2: 0.8451752138567498

In [ ]:
# 변수 중요도 시각화

In [106]:
# 모델저장
joblib.dump(model, 'model_lgbm.pkl')

['model_lgbm.pkl']

# 5.성능평가

- 가장 좋은 성능을 보였던 모델을 joblib.load() 함수를 사용해 불러옵니다.
- 불러온 모델로 새로운 데이터에 대해 예측을 수행합니다.

In [108]:
# 모델 불러오기
model = joblib.load('model_lgbm.pkl')

In [110]:
# 평가용 데이터 불러오기
path = 'https://raw.githubusercontent.com/jangrae/csv/master/insurance_test.csv'
new_data = pd.read_csv(path)

# 확인
new_data.head()

   age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

- 원본 데이터프레임을 유지하기 위해 새로운 데이터프레임으로 복사합니다.
- 복사된 데이터프레임에 대해 가변수화를 수행합니다.

In [112]:
# 데이터 복사
x_test = new_data.copy()

# 가변수화
dumm_cols = ['sex', 'smoker', 'region']
x_test = pd.get_dummies(x_test, columns=dumm_cols, drop_first=True, dtype=int)

# 확인
x_test.head()

,age,bmi,children,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,0,1,0,0,1
1,18,33.770,1,1,0,0,1,0
2,28,33.000,3,1,0,0,1,0
3,33,22.705,0,1,0,1,0,0
4,32,28.880,0,1,0,1,0,0

- 가변수화된 결과를 대상으로 예측을 수행합니다.
- 참고: 예측을 위해서는 모델이 학습했던 데이터(x_train)과 데이터 구조가 같아야 합니다.

In [114]:
# 예측하기
y_pred = model.predict(x_test)

# 확인
y_pred[:10]

array([19845.96378147,  4396.41506654,  6317.2410295 ,  4127.80999422,
        4303.035001  ,  4087.787513  ,  9200.25381408,  8385.09588094,
        8365.59130756, 13883.56084799])

- 예측 결과를 'charges_pred' 이름의 열로 원본 데이터프레임에 추가합니다.

In [116]:
# 결과 합기기
new_data['charges_pred'] = y_pred

# 확인
new_data.head()

   age     sex     bmi  children smoker     region  charges_pred
0   19  female  27.900         0    yes  southwest  19845.963781
1   18    male  33.770         1     no  southeast   4396.415067
2   28    male  33.000         3     no  southeast   6317.241029
3   33    male  22.705         0     no  northwest   4127.809994
4   32    male  28.880         0     no  northwest   4303.035001